[workspace]
resolver = "3"
members = [
    "crates/noxide",
    "crates/noxide-cli",
    "crates/noxide-macros",
    "crates/noxide-protocol",
    "crates/noxide-host",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.98"
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/mqqz/noxide"

[workspace.dependencies]
noxide = { path = "crates/noxide", version = "0.1.0" }
noxide-macros = { path = "crates/noxide-macros", version = "0.1.0" }
noxide-protocol = { path = "crates/noxide-protocol", version = "0.1.0" }
noxide-host = { path = "crates/noxide-host", version = "0.1.0" }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"

[profile.dev]
debug = 0

[profile.test]
debug = 0
